export const commonConstants = {
    DEFAULT_TROOPS: [
        {
            name: 'Avalon',
            units: [
                {
                    name: 'Avalon I',
                    img: 'images/avalon.png',
                    health: 32,
                    currentHealth: 32,
                    revenge: 1,
                    strength: 1,
                    defense: 0,
                    movement: 2,
                    agility: 3,
                    archery: 2,
                    crit: 1
                },
                {
                    name: 'Avalon II',
                    img: 'images/avalon.png',
                    health: 32,
                    currentHealth: 32,
                    revenge: 1,
                    strength: 1,
                    defense: 0,
                    movement: 2,
                    agility: 3,
                    archery: 2,
                    crit: 1
                },
                {
                    name: 'Avalon III',
                    img: 'images/avalon.png',
                    health: 32,
                    currentHealth: 32,
                    revenge: 1,
                    strength: 1,
                    defense: 0,
                    movement: 2,
                    agility: 3,
                    archery: 2,
                    crit: 1
                },
                {
                    name: 'Avalon IV',
                    img: 'images/avalon.png',
                    health: 32,
                    currentHealth: 32,
                    revenge: 1,
                    strength: 1,
                    defense: 0,
                    movement: 2,
                    agility: 3,
                    archery: 2,
                    crit: 1
                },
                {
                    name: 'Avalon V',
                    img: 'images/avalon.png',
                    health: 32,
                    currentHealth: 32,
                    revenge: 1,
                    strength: 1,
                    defense: 0,
                    movement: 2,
                    agility: 3,
                    archery: 2,
                    crit: 1
                }
            ]
        },
        {
            name: 'Konung',
            units: [
                {
                    name: 'Konung I',
                    img: 'images/avalon.png',
                    health: 32,
                    currentHealth: 32,
                    revenge: 1,
                    strength: 1,
                    defense: 0,
                    movement: 2,
                    agility: 3,
                    archery: 2,
                    crit: 1
                },
                {
                    name: 'Konung II',
                    img: 'images/konung.png',
                    health: 52,
                    currentHealth: 52,
                    revenge: 1,
                    strength: 2,
                    defense: 2,
                    movement: 1,
                    agility: 0,
                    archery: 0,
                    crit: 1
                },
                {
                    name: 'Konung III',
                    img: 'images/avalon.png',
                    health: 32,
                    currentHealth: 32,
                    revenge: 1,
                    strength: 1,
                    defense: 0,
                    movement: 2,
                    agility: 3,
                    archery: 2,
                    crit: 1
                },
                {
                    name: 'Konung IV',
                    img: 'images/konung.png',
                    health: 52,
                    currentHealth: 52,
                    revenge: 1,
                    strength: 2,
                    defense: 2,
                    movement: 1,
                    agility: 0,
                    archery: 0,
                    crit: 1
                },
                {
                    name: 'Konung V',
                    img: 'images/konung.png',
                    health: 52,
                    currentHealth: 52,
                    revenge: 1,
                    strength: 2,
                    defense: 2,
                    movement: 1,
                    agility: 0,
                    archery: 0,
                    crit: 1
                }
            ]
        }

    ],
    DEFAULT_UNIT: {
        name: '',
        img: '',
        health: 0,
        currentHealth: 0,
        revenge: 0,
        strength: 0,
        defense: 0,
        movement: 0,
        agility: 0,
        archery: 0,
        crit: 0
    },
    WAR_DWARFES: [
        {
            name: 'Dwarf I',
            img: 'images/troops/dwarf1',
            health: 58,
            currentHealth: 48,
            revenge: 1,
            strength: 3,
            defense: 1,
            movement: 2,
            agility: 0,
            archery: 0,
            crit: 2,
            weapon: ['K', 'A', 'P', 'MP']
        },
        {
            name: 'Dwarf II',
            img: 'images/troops/dwarf2',
            health: 42,
            currentHealth: 42,
            revenge: 1,
            strength: 2,
            defense: 2,
            movement: 2,
            agility: 0,
            archery: 0,
            crit: 1,
            weapon: ['K', 'A']
        },
        {
            name: 'Dwarf III',
            img: 'images/troops/dwarf3',
            health: 46,
            currentHealth: 46,
            revenge: 2,
            strength: 2,
            defense: 0,
            movement: 2,
            agility: 1,
            archery: 0,
            crit: 3,
            weapon: ['K', 'A', 'P', 'MP']
        },
        {
            name: 'Dwarf IV',
            img: 'images/troops/dwarf4',
            health: 42,
            currentHealth: 42,
            revenge: 1,
            strength: 2,
            defense: 2,
            movement: 2,
            agility: 0,
            archery: 0,
            crit: 1,
            weapon: ['K', 'A']
        },
        {
            name: 'Dwarf V',
            img: 'images/troops/dwarf5',
            health: 42,
            currentHealth: 42,
            revenge: 1,
            strength: 2,
            defense: 2,
            movement: 2,
            agility: 0,
            archery: 0,
            crit: 1,
            weapon: ['K', 'A']
        },
    ],
    ELFS_ELITARO: [
        {
            name: 'Elitaro I',
            img: 'images/troops/elitaro1',
            health: 64,
            currentHealth: 54,
            revenge: 1,
            strength: 3,
            defense: 1,
            movement: 2,
            agility: 1,
            archery: 0,
            crit: 1,
            weapon: ['K', 'A', 'P', 'MP']
        },
        {
            name: 'Elitaro II',
            img: 'images/troops/elitaro2',
            health: 52,
            currentHealth: 52,
            revenge: 1,
            strength: 3,
            defense: 2,
            movement: 1,
            agility: 0,
            archery: 0,
            crit: 1,
            weapon: ['K', 'A']
        },
        {
            name: 'Elitaro III',
            img: 'images/troops/elitaro3',
            health: 52,
            currentHealth: 52,
            revenge: 1,
            strength: 4,
            defense: 1,
            movement: 2,
            agility: 0,
            archery: 0,
            crit: 2,
            weapon: ['P', 'MP']
        },
        {
            name: 'Elitaro IV',
            img: 'images/troops/elitaro4',
            health: 52,
            currentHealth: 52,
            revenge: 1,
            strength: 2,
            defense: 1,
            movement: 1,
            agility: 1,
            archery: 0,
            crit: 1,
            weapon: ['P', 'MP']
        },
        {
            name: 'Elitaro V',
            img: 'images/troops/elitaro4',
            health: 50,
            currentHealth: 50,
            revenge: 1,
            strength: 1,
            defense: 0,
            movement: 3,
            agility: 3,
            archery: 2,
            crit: 1,
            weapon: ['K', 'A', 'P', 'MP']
        },
    ]
}