export const troopsConstants = {
    DWARFES: {
        name: "Combat Dwarfes",
        units: [
            {
                name: 'Dwarf I',
                img: 'images/troops/dwarf1.png',
                _troop_id: 'DWARFES',
                health: 58,
                currentHealth: 58,
                revenge: 1,
                currentRevenge: 1,
                strength: 3,
                defense: 1,
                movement: 2,
                agility: 0,
                archery: 0,
                crit: 2,
                weapon: ['K', 'A', 'P', 'MP']
            },
            {
                name: 'Dwarf II',
                img: 'images/troops/dwarf2.png',
                _troop_id: 'DWARFES',
                health: 42,
                currentHealth: 42,
                revenge: 1,
                currentRevenge: 1,
                strength: 2,
                defense: 2,
                movement: 2,
                agility: 0,
                archery: 0,
                crit: 1,
                weapon: ['K', 'A']
            },
            {
                name: 'Dwarf III',
                img: 'images/troops/dwarf3.png',
                _troop_id: 'DWARFES',
                health: 46,
                currentHealth: 46,
                revenge: 2,
                currentRevenge: 2,
                strength: 2,
                defense: 0,
                movement: 2,
                agility: 1,
                archery: 0,
                crit: 3,
                weapon: ['K', 'A', 'P', 'MP']
            },
            {
                name: 'Dwarf IV',
                img: 'images/troops/dwarf4.png',
                _troop_id: 'DWARFES',
                health: 42,
                currentHealth: 42,
                revenge: 1,
                currentRevenge: 1,
                strength: 2,
                defense: 2,
                movement: 2,
                agility: 0,
                archery: 0,
                crit: 1,
                weapon: ['K', 'A']
            },
            {
                name: 'Dwarf V',
                img: 'images/troops/dwarf5.png',
                _troop_id: 'DWARFES',
                health: 42,
                currentHealth: 42,
                revenge: 1,
                currentRevenge: 1,
                strength: 2,
                defense: 2,
                movement: 2,
                agility: 0,
                archery: 0,
                crit: 1,
                weapon: ['K', 'A']
            }
        ]
    },
    ELITARO: {
        name: "Elitaro Armored Elfves",
        units: [
            {
                name: 'Elitaro I',
                img: 'images/troops/elitaro1.png',
                _troop_id: 'ELITARO',
                health: 64,
                currentHealth: 64,
                revenge: 1,
                currentRevenge: 1,
                strength: 3,
                defense: 1,
                movement: 2,
                agility: 1,
                archery: 0,
                crit: 1,
                weapon: ['K', 'A', 'P', 'MP']
            },
            {
                name: 'Elitaro II',
                img: 'images/troops/elitaro2.png',
                _troop_id: 'ELITARO',
                health: 52,
                currentHealth: 52,
                revenge: 1,
                currentRevenge: 1,
                strength: 3,
                defense: 2,
                movement: 1,
                agility: 0,
                archery: 0,
                crit: 1,
                weapon: ['K', 'A']
            },
            {
                name: 'Elitaro III',
                img: 'images/troops/elitaro3.png',
                _troop_id: 'ELITARO',
                health: 52,
                currentHealth: 52,
                revenge: 1,
                currentRevenge: 1,
                strength: 4,
                defense: 1,
                movement: 2,
                agility: 0,
                archery: 0,
                crit: 2,
                weapon: ['P', 'MP']
            },
            {
                name: 'Elitaro IV',
                img: 'images/troops/elitaro4.png',
                _troop_id: 'ELITARO',
                health: 52,
                currentHealth: 52,
                revenge: 1,
                currentRevenge: 1,
                strength: 2,
                defense: 1,
                movement: 1,
                agility: 1,
                archery: 0,
                crit: 1,
                weapon: ['P', 'MP']
            },
            {
                name: 'Elitaro V',
                img: 'images/troops/elitaro5.png',
                _troop_id: 'ELITARO',
                health: 50,
                currentHealth: 50,
                revenge: 1,
                currentRevenge: 1,
                strength: 1,
                defense: 0,
                movement: 3,
                agility: 3,
                archery: 2,
                crit: 1,
                weapon: ['K', 'A', 'P', 'MP']
            },
        ]
    },
    DARK_KNIGHTS: {
        name: "Dark Knights",
        units: [
            {
                name: 'Dark Knight I',
                img: 'images/troops/dark_knight1.png',
                _troop_id: 'DARK_KNIGHTS',
                health: 56,
                currentHealth: 56,
                revenge: 1,
                currentRevenge: 1,
                strength: 4,
                defense: 2,
                movement: 2,
                agility: 0,
                archery: 0,
                crit: 1,
                weapon: ['P', 'MP']
            },
            {
                name: 'Dark Knight II',
                img: 'images/troops/dark_knight2.png',
                _troop_id: 'DARK_KNIGHTS',
                health: 46,
                currentHealth: 46,
                revenge: 1,
                currentRevenge: 1,
                strength: 4,
                defense: 2,
                movement: 0,
                agility: 0,
                archery: 0,
                crit: 2,
                weapon: ['P', 'MP']
            },
            {
                name: 'Dark Knight III',
                img: 'images/troops/dark_knight3.png',
                _troop_id: 'DARK_KNIGHTS',
                health: 44,
                currentHealth: 44,
                revenge: 2,
                currentRevenge: 2,
                strength: 4,
                defense: 2,
                movement: 1,
                agility: 0,
                archery: 0,
                crit: 1,
                weapon: ['K', 'A']
            },
            {
                name: 'Dark Knight IV',
                img: 'images/troops/dark_knight4.png',
                _troop_id: 'DARK_KNIGHTS',
                health: 44,
                currentHealth: 44,
                revenge: 1,
                currentRevenge: 1,
                strength: 3,
                defense: 0,
                movement: 1,
                agility: 1,
                archery: 0,
                crit: 3,
                weapon: ['P', 'MP']
            },
            {
                name: 'Dark Knight V',
                img: 'images/troops/dark_knight5.png',
                _troop_id: 'DARK_KNIGHTS',
                health: 40,
                currentHealth: 40,
                revenge: 1,
                currentRevenge: 1,
                strength: 2,
                defense: 0,
                movement: 2,
                agility: 2,
                archery: 0,
                crit: 1,
                weapon: ['K', 'A', 'P', 'MP']
            },
        ]
    },
    PALADINS: {
        name: "Orden Paladin",
        units: [
            {
                name: 'Paladin I',
                img: 'images/troops/paladin1.png',
                _troop_id: 'PALADINS',
                health: 60,
                currentHealth: 60,
                revenge: 1,
                currentRevenge: 1,
                strength: 4,
                defense: 2,
                movement: 2,
                agility: 0,
                archery: 0,
                crit: 1,
                weapon: ['K', 'A','P', 'MP']
            },
            {
                name: 'Paladin II',
                img: 'images/troops/paladin2.png',
                _troop_id: 'PALADINS',
                health: 46,
                currentHealth: 46,
                revenge: 1,
                currentRevenge: 1,
                strength: 4,
                defense: 2,
                movement: 1,
                agility: 0,
                archery: 0,
                crit: 2,
                weapon: ['K', 'A']
            },
            {
                name: 'Paladin III',
                img: 'images/troops/paladin3.png',
                _troop_id: 'PALADINS',
                health: 44,
                currentHealth: 44,
                revenge: 1,
                currentRevenge: 1,
                strength: 3,
                defense: 3,
                movement: 1,
                agility: 0,
                archery: 0,
                crit: 1,
                weapon: ['K', 'A']
            },
            {
                name: 'Paladin IV',
                img: 'images/troops/paladin4.png',
                _troop_id: 'PALADINS',
                health: 44,
                currentHealth: 44,
                revenge: 1,
                currentRevenge: 1,
                strength: 3,
                defense: 1,
                movement: 2,
                agility: 1,
                archery: 0,
                crit: 2,
                weapon: ['P', 'MP']
            },
            {
                name: 'Paladin V',
                img: 'images/troops/paladin5.png',
                _troop_id: 'PALADINS',
                health: 46,
                currentHealth: 46,
                revenge: 1,
                currentRevenge: 1,
                strength: 1,
                defense: 2,
                movement: 2,
                agility: 1,
                archery: 2,
                crit: 1,
                weapon: ['P', 'MP']
            },
            
        ]
    },
    AVALON: {
        name: "Avalon Elfs",
        units: [
            {
                name: 'Avalon Elf I',
                img: 'images/troops/avalon1.png',
                _troop_id: 'AVALON',
                health: 48,
                currentHealth: 48,
                revenge: 1,
                currentRevenge: 1,
                strength: 1,
                defense: 0,
                movement: 3,
                agility: 4,
                archery: 3,
                crit: 0,
                weapon: ['K', 'A','P', 'MP']
            },
            {
                name: 'Avalon Elf II',
                img: 'images/troops/avalon2.png',
                _troop_id: 'AVALON',
                health: 38,
                currentHealth: 38,
                revenge: 1,
                currentRevenge: 1,
                strength: 1,
                defense: 0,
                movement: 3,
                agility: 3,
                archery: 2,
                crit: 1,
                weapon: ['K', 'A','P', 'MP']
            },
            {
                name: 'Avalon Elf III',
                img: 'images/troops/avalon3.png',
                _troop_id: 'AVALON',
                health: 38,
                currentHealth: 38,
                revenge: 1,
                currentRevenge: 1,
                strength: 1,
                defense: 0,
                movement: 3,
                agility: 3,
                archery: 2,
                crit: 1,
                weapon: ['K', 'A','P', 'MP']
            },
            {
                name: 'Avalon Elf IV',
                img: 'images/troops/avalon4.png',
                _troop_id: 'AVALON',
                health: 38,
                currentHealth: 38,
                revenge: 1,
                currentRevenge: 1,
                strength: 1,
                defense: 0,
                movement: 3,
                agility: 3,
                archery: 2,
                crit: 1,
                weapon: ['K', 'A','P', 'MP']
            },
            {
                name: 'Avalon Elf V',
                img: 'images/troops/avalon5.png',
                _troop_id: 'AVALON',
                health: 38,
                currentHealth: 38,
                revenge: 1,
                currentRevenge: 1,
                strength: 1,
                defense: 0,
                movement: 3,
                agility: 3,
                archery: 2,
                crit: 1,
                weapon: ['K', 'A','P', 'MP']
            },
        ]
    },
    SKELETONS: {
        name: "Skeletons",
        units: [
            {
                name: 'Skeleton I',
                img: 'images/troops/skeleton1.png',
                _troop_id: 'SKELETONS',
                health: 44,
                currentHealth: 44,
                revenge: 1,
                currentRevenge: 1,
                strength: 2,
                defense: 1,
                movement: 1,
                agility: 1,
                archery: 0,
                crit: 1,
                weapon: ['P', 'MP']
            },
            {
                name: 'Skeleton II',
                img: 'images/troops/skeleton2.png',
                _troop_id: 'SKELETONS',
                health: 36,
                currentHealth: 36,
                revenge: 1,
                currentRevenge: 1,
                strength: 2,
                defense: 0,
                movement: 1,
                agility: 1,
                archery: 0,
                crit: 2,
                weapon: ['K', 'A','P']
            },
            {
                name: 'Skeleton III',
                img: 'images/troops/skeleton3.png',
                _troop_id: 'SKELETONS',
                health: 36,
                currentHealth: 36,
                revenge: 1,
                currentRevenge: 1,
                strength: 2,
                defense: 0,
                movement: 1,
                agility: 1,
                archery: 0,
                crit: 2,
                weapon: ['K', 'A','P']
            },
            {
                name: 'Skeleton IV',
                img: 'images/troops/skeleton4.png',
                _troop_id: 'SKELETONS',
                health: 36,
                currentHealth: 36,
                revenge: 1,
                currentRevenge: 1,
                strength: 2,
                defense: 0,
                movement: 1,
                agility: 1,
                archery: 0,
                crit: 2,
                weapon: ['K', 'A','P']
            },
            {
                name: 'Skeleton V',
                img: 'images/troops/skeleton5.png',
                _troop_id: 'SKELETONS',
                health: 34,
                currentHealth: 34,
                revenge: 1,
                currentRevenge: 1,
                strength: 2,
                defense: 0,
                movement: 1,
                agility: 1,
                archery: 0,
                crit: 2,
                weapon: ['P', 'MP']
            },
            {
                name: 'Skeleton VI',
                img: 'images/troops/skeleton6.png',
                _troop_id: 'SKELETONS',
                health: 34,
                currentHealth: 34,
                revenge: 1,
                currentRevenge: 1,
                strength: 2,
                defense: 0,
                movement: 1,
                agility: 1,
                archery: 0,
                crit: 2,
                weapon: ['P', 'MP']
            }
        ]
    },
    UNICORN: {
        name: "Unicorn Orden",
        units: [
            {
                name: 'Unicorn I',
                img: 'images/troops/unicorn1.png',
                _troop_id: 'UNICORN',
                health: 54,
                currentHealth: 54,
                revenge: 2,
                currentRevenge: 2,
                strength: 3,
                defense: 1,
                movement: 1,
                agility: 0,
                archery: 0,
                crit: 1,
                weapon: ['A','K','P', 'MP']
            },
            {
                name: 'Unicorn II',
                img: 'images/troops/unicorn2.png',
                _troop_id: 'UNICORN',
                health: 40,
                currentHealth: 40,
                revenge: 2,
                currentRevenge: 2, 
                strength: 3,
                defense: 1,
                movement: 1,
                agility: 0,
                archery: 0,
                crit: 1,
                weapon: ['A','K','P']
            },
            {
                name: 'Unicorn III',
                img: 'images/troops/unicorn3.png',
                _troop_id: 'UNICORN',
                health: 42,
                currentHealth: 42,
                revenge: 2,
                currentRevenge: 2,
                strength: 3,
                defense: 2,
                movement: 0,
                agility: 0,
                archery: 0,
                crit: 1,
                weapon: ['P','MP']
            },
            {
                name: 'Unicorn IV',
                img: 'images/troops/unicorn4.png',
                _troop_id: 'UNICORN',
                health: 40,
                currentHealth: 40,
                revenge: 2,
                currentRevenge: 2,
                strength: 3,
                defense: 1,
                movement: 1,
                agility: 1,
                archery: 0,
                crit: 1,
                weapon: ['A','K', 'P']
            },
            {
                name: 'Unicorn V',
                img: 'images/troops/unicorn5.png',
                _troop_id: 'UNICORN',
                health: 44,
                currentHealth: 44,
                revenge: 2,
                currentRevenge: 2,
                strength: 2,
                defense: 1,
                movement: 1,
                agility: 0,
                archery: 1,
                crit: 1,
                weapon: ['A','K', 'P']
            },
        ]
    },
    PIRATES: {
        name: "Pirates of dark water",
        units: [
            {
                name: 'Pirate I',
                img: 'images/troops/pirate1.png',
                _troop_id: 'PIRATES',
                health: 48,
                currentHealth: 48,
                revenge: 1,
                currentRevenge: 1,
                strength: 1,
                defense: 0,
                movement: 3,
                agility: 2,
                archery: 1,
                crit: 1,
                weapon: ['A','K','P', 'MP']
            },
            {
                name: 'Pirate II',
                img: 'images/troops/pirate2.png',
                _troop_id: 'PIRATES',
                health: 38,
                currentHealth: 38,
                revenge: 2,
                currentRevenge: 2,
                strength: 1,
                defense: 0,
                movement: 2,
                agility: 1,
                archery: 3,
                crit: 1,
                weapon: ['P', 'MP']
            },
            {
                name: 'Pirate III',
                img: 'images/troops/pirate3.png',
                _troop_id: 'PIRATES',
                health: 38,
                currentHealth: 38,
                revenge: 1,
                currentRevenge: 1,
                strength: 1,
                defense: 0,
                movement: 2,
                agility: 1,
                archery: 2,
                crit: 1,
                weapon: ['P', 'MP']
            },
            {
                name: 'Pirate IV',
                img: 'images/troops/pirate4.png',
                _troop_id: 'PIRATES',
                health: 40,
                currentHealth: 40,
                revenge: 2,
                currentRevenge: 2,
                strength: 2,
                defense: 0,
                movement: 2,
                agility: 2,
                archery: 1,
                crit: 2,
                weapon: ['A', 'K', 'P']
            },
            {
                name: 'Pirate IV',
                img: 'images/troops/pirate5.png',
                _troop_id: 'PIRATES',
                health: 36,
                currentHealth: 36,
                revenge: 1,
                currentRevenge: 1,
                strength: 0,
                defense: 0,
                movement: 2,
                agility: 1,
                archery: 2,
                crit: 1,
                weapon: ['A', 'K', 'P']
            }
        ]
    },
    GIDRA: {
        name: `Gidras' Squad`,
        units: [
            {
                name: 'Gidra I',
                img: 'images/troops/gidra1.png',
                _troop_id: 'GIDRA',
                health: 50,
                currentHealth: 50,
                revenge: 1,
                currentRevenge: 1,
                strength: 2,
                defense: 0,
                movement: 3,
                agility: 2,
                archery: 0,
                crit: 1,
                weapon: ['A', 'K', 'P', 'MP']
            },
            {
                name: 'Gidra II',
                img: 'images/troops/gidra2.png',
                _troop_id: 'GIDRA',
                health: 32,
                currentHealth: 32,
                revenge: 1,
                currentRevenge: 1,
                strength: 2,
                defense: 0,
                movement: 2,
                agility: 1,
                archery: 0,
                crit: 1,
                weapon: ['K', 'P']
            },
            {
                name: 'Gidra III',
                img: 'images/troops/gidra3.png',
                _troop_id: 'GIDRA',
                health: 32,
                currentHealth: 32,
                revenge: 1,
                currentRevenge: 1,
                strength: 2,
                defense: 0,
                movement: 2,
                agility: 1,
                archery: 0,
                crit: 1,
                weapon: ['A','K','P','MP']
            },
            {
                name: 'Gidra IV',
                img: 'images/troops/gidra4.png',
                _troop_id: 'GIDRA',
                health: 32,
                currentHealth: 32,
                revenge: 1,
                currentRevenge: 1,
                strength: 2,
                defense: 0,
                movement: 2,
                agility: 1,
                archery: 0,
                crit: 1,
                weapon: ['K', 'P']
            },
            {
                name: 'Gidra V',
                img: 'images/troops/gidra5.png',
                _troop_id: 'GIDRA',
                health: 32,
                currentHealth: 32,
                revenge: 1,
                currentRevenge: 1,
                strength: 2,
                defense: 0,
                movement: 2,
                agility: 1,
                archery: 0,
                crit: 2,
                weapon: ['K', 'P']
            },
            {
                name: 'Gidra VI',
                img: 'images/troops/gidra6.png',
                _troop_id: 'GIDRA',
                health: 32,
                currentHealth: 32,
                revenge: 2,
                currentRevenge: 2,
                strength: 2,
                defense: 0,
                movement: 2,
                agility: 1,
                archery: 0,
                crit: 2,
                weapon: ['A','K','P','MP']
            },
        ]
    },
    KONUNG: {
        name: `Konung's Army`,
        units: [
            {
                name: 'Konung I',
                img: 'images/troops/konung1.png',
                _troop_id: 'KONUNG',
                health: 50,
                modification: {},
                currentHealth: 50,
                revenge: 1,
                currentRevenge: 1,
                strength: 2,
                defense: 2,
                movement: 0,
                agility: 0,
                archery: 0,
                crit: 1,
                weapon: ['A', 'K', 'P', 'MP']
            },
            {
                name: 'Konung II',
                img: 'images/troops/konung2.png',
                _troop_id: 'KONUNG',
                health: 36,
                modification: {},
                currentHealth: 36,
                revenge: 1,
                currentRevenge: 1,
                strength: 1,
                defense: 1,
                movement: 1,
                agility: 1,
                archery: 1,
                crit: 1,
                weapon: [ 'P', 'MP']
            },
            {
                name: 'Konung III',
                img: 'images/troops/konung3.png',
                _troop_id: 'KONUNG',
                health: 40,
                modification: {},
                currentHealth: 40,
                revenge: 2,
                currentRevenge: 2,
                strength: 3,
                defense: 2,
                movement: 1,
                agility: 1,
                archery: 0,
                crit: 1,
                weapon: ['A', 'K']
            },
            {
                name: 'Konung IV',
                img: 'images/troops/konung4.png',
                _troop_id: 'KONUNG',
                health: 38,
                modification: {},
                currentHealth: 38,
                revenge: 1,
                currentRevenge: 1,
                strength: 2,
                defense: 2,
                movement: 1,
                agility: 1,
                archery: 0,
                crit: 2,
                weapon: ['A', 'K']
            },
            {
                name: 'Konung V',
                img: 'images/troops/konung5.png',
                _troop_id: 'KONUNG',
                health: 36,
                modification: {},
                currentHealth: 36,
                revenge: 1,
                currentRevenge: 1,
                strength: 1,
                defense: 1,
                movement: 1,
                agility: 1,
                archery: 1,
                crit: 1,
                weapon: [ 'P', 'MP']
            }
        ]
    },
    WAREWOLVES: {
        name: `Warewolves`,
        units: [
            {
                name: 'Warewolf I',
                img: 'images/troops/warewolf1.png',
                _troop_id: 'WAREWOLVES',
                health: 68,
                currentHealth: 68,
                revenge: 1,
                currentRevenge: 1,
                strength: 3,
                defense: 1,
                movement: 6,
                agility: 2,
                archery: 0,
                crit: 3,
                weapon: []
            },
            {
                name: 'Warewolf II',
                img: 'images/troops/warewolf2.png',
                _troop_id: 'WAREWOLVES',
                health: 52,
                currentHealth: 52,
                revenge: 2,
                currentRevenge: 2,
                strength: 4,
                defense: 2,
                movement: 4,
                agility: 2,
                archery: 0,
                crit: 1,
                weapon: []
            },
            {
                name: 'Warewolf III',
                img: 'images/troops/warewolf3.png',
                _troop_id: 'WAREWOLVES',
                health: 48,
                currentHealth: 48,
                revenge: 1,
                currentRevenge: 1,
                strength: 4,
                defense: 1,
                movement: 5,
                agility: 2,
                archery: 0,
                crit: 2,
                weapon: []
            },
            {
                name: 'Warewolf III',
                img: 'images/troops/warewolf4.png',
                _troop_id: 'WAREWOLVES',
                health: 52,
                currentHealth: 52,
                revenge: 1,
                currentRevenge: 1,
                strength: 4,
                defense: 2,
                movement: 4,
                agility: 2,
                archery: 0,
                crit: 1,
                weapon: []
            },
        ]
    },
    KENTAVERS: {
        name: `Kentavres`,
        units: [
            {
                name: 'Kentavr I',
                img: 'images/troops/kentavr1.png',
                _troop_id: 'KENTAVERS',
                health: 80,
                currentHealth: 80,
                revenge: 4,
                currentRevenge: 4,
                strength: 5,
                defense: 2,
                movement: 6,
                agility: 0,
                archery: 0,
                crit: 2,
                weapon: []
            },
            {
                name: 'Kentavr II',
                img: 'images/troops/kentavr2.png',
                _troop_id: 'KENTAVERS',
                health: 68,
                currentHealth: 68,
                revenge: 4,
                currentRevenge: 4,
                strength: 3,
                defense: 2,
                movement: 5,
                agility: 0,
                archery: 2,
                crit: 2,
                weapon: []
            },
            {
                name: 'Kentavr III',
                img: 'images/troops/kentavr3.png',
                _troop_id: 'KENTAVERS',
                health: 66,
                currentHealth: 66,
                revenge: 4,
                currentRevenge: 4,
                strength: 4,
                defense: 2,
                movement: 6,
                agility: 0,
                archery: 0,
                crit: 2,
                weapon: []
            },
            {
                name: 'Kentavr IV',
                img: 'images/troops/kentavr4.png',
                _troop_id: 'KENTAVERS',
                health: 66,
                currentHealth: 66,
                revenge: 4,
                currentRevenge: 4,
                strength: 4,
                defense: 2,
                movement: 6,
                agility: 0,
                archery: 0,
                crit: 2,
                weapon: []
            },
        ]
    }
} 